version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    container_name: caddy
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  frps:
    image: snowdreamtech/frps:latest
    restart: unless-stopped
    container_name: frps
    network_mode: host
    volumes:
      - ./frps.toml:/etc/frp/frps.toml:ro

volumes:
  caddy_data:
  caddy_config:
